-- User-defined lists (bookmarks, remind-me-later, custom playlists).
-- Two system lists are seeded so the UI always has something to show.

CREATE TABLE IF NOT EXISTS lists (
	id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	slug        TEXT UNIQUE NOT NULL,
	name        TEXT NOT NULL,
	emoji       TEXT,
	is_system   BOOLEAN NOT NULL DEFAULT FALSE,
	created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS list_games (
	list_id   INTEGER NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
	appid     INTEGER NOT NULL REFERENCES games(appid) ON DELETE CASCADE,
	note      TEXT,
	added_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY (list_id, appid)
);

CREATE INDEX IF NOT EXISTS idx_list_games_appid ON list_games(appid);

INSERT INTO lists (slug, name, emoji, is_system) VALUES
	('bookmarks',    'Bookmarks',       '⭐', TRUE),
	('remind_later', 'Remind me later', '⏰', TRUE)
ON CONFLICT (slug) DO NOTHING;
