-- "Curated" — user-named saved searches that re-run as a live query each
-- time they're opened. Distinct from `lists` (static membership) — different
-- semantics and lifecycle, so a separate table avoids nullable cruft on
-- both sides.

CREATE TABLE IF NOT EXISTS saved_searches (
	id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	slug        TEXT UNIQUE NOT NULL,
	name        TEXT NOT NULL,
	emoji       TEXT,
	query       TEXT NOT NULL,
	tag_filter  TEXT,
	sort_order  TEXT,
	created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_saved_searches_created
	ON saved_searches(created_at);
